# list all the text{iindex}.txt files
INDICES = [str(i) for i in range(1, 3+1)]

rule all:
	input:
		"../results/summary.csv"

rule summary:
	input:
		# creates a list ["../results/counts1.txt", "../results/counts2.txt",...]
		expand(f"../results/counts{index}.txt" for index in INDICES)
	output:
		"../results/summary.csv"
	run:
		# find the number of occurrences of a word in a text 
		with open(output[0], 'w') as fout:
			fout.write('filename,count\n')
			for filename in input:
				with open(filename) as f: # open each file
					n = int(f.read()) # read the content of the file
					fout.write(f'{n}\n')

rule countWord:
	input:
		"../data/text{index}.txt"
	output:
		"../results/counts{index}.txt"
	shell:
		# find all occurrences of the word 'the'
		"grep -woi the {input} | wc -l > {output}"


