# import the Python glob module
from glob import glob

SUM_FILE = "../results/sum.txt"

rule all:
	input:
		# the single output file that will contain the sum
		SUM_FILE

rule add:
	input:
		# the input files each contain a number
		glob("../data/mydata_*.txt")
	output:
		"../results/sum.txt"
	run:
		# add the number in the input files using Python code
		res = 0 # stores the sum
		for filename in input: # input is a list of file names
			# open each file
			with open(filename) as f:
				# read the content of the file
				n = int(f.read())
				# increment the sum
				res += n
		# write out the result
		with open(output[0], 'w') as out:
			out.write(f'{res}\n')


