A = "../results/A.txt"
B = "../results/B.txt"

rule all:
	input:
		B

rule produceA:
	output:
		A
	shell:
		"touch {output}"

rule produceBFromA:
	input:
		A
	output:
		B
	shell:
		"cp {input} {output}"

