A = "../results/A.txt"
B = "../results/B.txt"
C = "../results/C.txt"

rule all:
    input:
        C,

rule produceA:
    output:
        A,
    shell:
        'echo "10" > {output}'

rule produceBFromA:
    input:
        A,
    output:
        B,
    shell:
        # add 1 to the number in A.txt
        'echo $(($(cat {input}) + 1)) > {output}'

rule produceCFromAB:
    input:
        A, B
    output:
        C,
    shell:
        # concatenate the contents of A and B into C
        "cat {input} > {output}"

